trigger:
  - master

pool:
  vmImage: "windows-latest"

steps:
  - task: Docker@2
    displayName: "Build and push image"
    inputs:
      containerRegistry: "Docker Lambda3"
      repository: "lambda3/azure-pipelines-agent-windows"
      tags: latest
