version: "2"
services:
  agent:
    image: lambda3/azure-pipelines-agent-windows
    environment:
      - VS_TENANT=${VS_TENANT:?Variable VS_TENANT is required.}
      - AGENT_PAT=${AGENT_PAT:?Variable AGENT_PAT is required.}
      - AGENT_POOL=${AGENT_POOL:-Default}
    volumes:
      - c:\agent\_works:c:\agent\_works
      - source: '\\.\pipe\docker_engine'
        target: '\\.\pipe\docker_engine'
        type: npipe
    stdin_open: true
    tty: true
    restart: always
