trigger:
  branches:
    include:
      - master
  paths:
    include:
      - agent/*
    exclude:
      - "*/*.md"
      - "*/*.txt"

stages:
- stage: build
  displayName: Build
  jobs:
  - job: build
    displayName: Build
    timeoutInMinutes: 360
    cancelTimeoutInMinutes: 1
    pool:
      #vmImage: "windows-latest"
      name: Default
      demands:
        - agent.os -equals Windows_NT

    steps:
      - task: Docker@2
        displayName: "Build image"
        inputs:
          command: build
          containerRegistry: "Docker Lambda3"
          repository: "lambda3/azure-pipelines-agent-windows"
          tags: latest
          Dockerfile: "$(Build.SourcesDirectory)/agent/Dockerfile"
          arguments: "--memory 4GB --network lan_net"

      - task: Docker@2
        displayName: "Push image"
        inputs:
          containerRegistry: "Docker Lambda3"
          repository: "lambda3/azure-pipelines-agent-windows"
          command: push
          tags: latest
