version: '2'
services:
  agent:
    image: lambda3/azure-pipelines-agent-windows
    environment:
      AGENT_PAT:
      AGENT_POOL:
      VS_TENANT:
    stdin_open: true
    tty: true
    restart: always
