# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Publish Docker image

on:
  workflow_dispatch:
    inputs:
      skipUpdateCheck:
        description: "Skip checking if image needs update and always run the build steps"
        required: false
        default: false
        type: boolean
      push:
        description: "Push to docker hub"
        required: false
        default: false
        type: boolean
  schedule:
    - cron: "5 3 * * *"
  push:
    branches:
      - "*"
    tags:
      - "*"
    paths-ignore:
      - "**.md"
      - "**.txt"
      - ".gitattribute"
      - ".gitignore"
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "**.md"
      - "**.txt"
      - ".gitattribute"
      - ".gitignore"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: windows-2019
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Check if update available
        id: check
        uses: giggio/docker-image-update-checker@v2
        with:
          base-image: mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019
          image: lambda3/azure-pipelines-agent-windows
          os: windows
          verbose: true
        if: ${{ github.event_name == 'schedule' }}

      - name: Extract metadata (tags, labels) for Docker (Latest image)
        id: meta_latest
        uses: docker/metadata-action@v4
        with:
          images: lambda3/azure-pipelines-agent-windows
          flavor: |
            latest=false
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/latest' }}
            type=ref,event=branch,enable=${{ github.ref != 'refs/heads/latest' }}
            type=ref,event=tag
        if: ${{ success() && (contains(fromJson('["push", "pull_request"]'), github.event_name) || (steps.check.outputs.needs-updating == 'true' && github.event_name == 'schedule') || (inputs.skipUpdateCheck && github.event_name == 'workflow_dispatch')) }}

      - name: Build image (latest)
        working-directory: ./agent/
        run: |
          $ErrorActionPreference = "Stop"
          Invoke-Expression "docker build --pull $($env:TAGS.Split("`n") | % { '-t "' + $_ + '"' }) $($env:LABELS.Split("`n") | % { '--label "' + $_ + '"' }) ."
          if ($LASTEXITCODE -ne 0) { throw "Docker build failed." }
        env:
          TAGS: ${{ steps.meta_latest.outputs.tags }}
          LABELS: ${{ steps.meta_latest.outputs.labels }}
        if: ${{ success() && (contains(fromJson('["push", "pull_request"]'), github.event_name) || (steps.check.outputs.needs-updating == 'true' && github.event_name == 'schedule') || (inputs.skipUpdateCheck && github.event_name == 'workflow_dispatch')) }}

      - name: Extract metadata (tags, labels) for Docker (Docker image)
        id: meta_docker
        uses: docker/metadata-action@v4
        with:
          images: lambda3/azure-pipelines-agent-windows
          flavor: |
            latest=false
          tags: |
            type=raw,value=docker,enable=${{ github.ref == 'refs/heads/latest' }}
            type=ref,suffix=-docker,event=branch,enable=${{ github.ref != 'refs/heads/latest' }}
            type=ref,suffix=-docker,event=tag
        if: ${{ success() && (contains(fromJson('["push", "pull_request"]'), github.event_name) || (steps.check.outputs.needs-updating == 'true' && github.event_name == 'schedule') || (inputs.skipUpdateCheck && github.event_name == 'workflow_dispatch')) }}

      - name: Build image (docker)
        working-directory: ./agent-docker/
        run: |
          $ErrorActionPreference = "Stop"
          Invoke-Expression "docker build --build-arg FROM=${{ steps.meta_latest.outputs.tags }} $($env:TAGS.Split("`n") | % { '-t "' + $_ + '"' }) $($env:LABELS.Split("`n") | % { '--label "' + $_ + '"' }) ."
          if ($LASTEXITCODE -ne 0) { throw "Docker build failed." }
        env:
          TAGS: ${{ steps.meta_docker.outputs.tags }}
          LABELS: ${{ steps.meta_docker.outputs.labels }}
        if: ${{ success() && (contains(fromJson('["push", "pull_request"]'), github.event_name) || (steps.check.outputs.needs-updating == 'true' && github.event_name == 'schedule') || (inputs.skipUpdateCheck && github.event_name == 'workflow_dispatch')) }}

      - name: Docker login
        id: docker_login
        run: |
          $ErrorActionPreference = "Stop"
          docker login -u lambdatres -p $env:DOCKER_PASSWORD
          if ($LASTEXITCODE -ne 0) { throw "Docker login failed." }
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ success() && ((github.event_name == 'push' && (github.ref == 'refs/heads/latest' || startsWith(github.ref, 'refs/tags/'))) || (steps.check.outputs.needs-updating == 'true' && github.event_name == 'schedule') || (inputs.skipUpdateCheck && inputs.push && github.event_name == 'workflow_dispatch')) }}

      - name: Push image (latest)
        run: |
          $ErrorActionPreference = "Stop"
          $($env:TAGS.Split("`n") | % {
            docker push $_
            if ($LASTEXITCODE -ne 0) { throw "Docker push failed." }
          })
        env:
          TAGS: ${{ steps.meta_latest.outputs.tags }}
        if: ${{ success() && ((github.event_name == 'push' && (github.ref == 'refs/heads/latest' || startsWith(github.ref, 'refs/tags/'))) || (steps.check.outputs.needs-updating == 'true' && github.event_name == 'schedule') || (inputs.skipUpdateCheck && inputs.push && github.event_name == 'workflow_dispatch')) }}

      - name: Push image (docker)
        run: |
          $ErrorActionPreference = "Stop"
          $($env:TAGS.Split("`n") | % {
            docker push $_
            if ($LASTEXITCODE -ne 0) { throw "Docker push failed." }
          })
        env:
          TAGS: ${{ steps.meta_docker.outputs.tags }}
        if: ${{ success() && ((github.event_name == 'push' && (github.ref == 'refs/heads/latest' || startsWith(github.ref, 'refs/tags/'))) || (steps.check.outputs.needs-updating == 'true' && github.event_name == 'schedule') || (inputs.skipUpdateCheck && inputs.push && github.event_name == 'workflow_dispatch')) }}

      - name: Docker logout
        run: docker logout
        if: ${{ always() && steps.docker_login.outcome != 'skipped' }}
